#!/usr/bin/env node
// Generate src/version.ts from package.json so the version string is
// available at runtime without reading package.json from disk.
//
// Why: in the `bun build --compile` single-file binary, the host's
// own package.json is not on the embedded virtual filesystem at
// `/$bunfs/root/`. `readFileSync(new URL('../package.json', ...))`
// throws ENOENT and `--version` ends up printing 'unknown'. Baking
// the version string at build time guarantees a real number ships
// inside the binary.
//
// Re-run: `pnpm -C packages/host build:version`. The `build` script
// invokes this automatically before `tsc`, so a normal `pnpm -r build`
// keeps the committed src/version.ts in sync with package.json.

import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PKG_ROOT = join(__dirname, '..')
const PKG_JSON = join(PKG_ROOT, 'package.json')
const OUT_FILE = join(PKG_ROOT, 'src', 'version.ts')

const pkg = JSON.parse(await readFile(PKG_JSON, 'utf8'))
const version = String(pkg.version ?? 'unknown')

const content = `// AUTO-GENERATED by scripts/build-version.mjs. Do not edit by hand.
// Re-run \`pnpm -C packages/host build:version\` after bumping the
// version in package.json (or just \`pnpm -r build\` — the host's
// build script runs this generator before tsc).
//
// Why bake the version: in the bun --compile single-file binary,
// reading package.json from disk fails because it isn't on the
// embedded /$bunfs/ virtual filesystem. main.ts falls back to this
// constant whenever the disk read throws.

export const BAKED_VERSION = ${JSON.stringify(version)}
`

await writeFile(OUT_FILE, content, 'utf8')
process.stdout.write(`build-version: pinned ${version} → ${OUT_FILE}\n`)
