/**
 * In-process template generator for `aipehub new python-agent <name>`.
 * Mirror of `./ts-agent.ts` for Python sidecars. Returns the three
 * files the scaffold writes.
 */

export interface PyTemplateOpts {
  name: string
  id: string
  capabilities: string
  includeServices: boolean
}

export interface PyTemplateOutput {
  pyproject: string
  source: string
  readme: string
}

export function renderPyTemplate(opts: PyTemplateOpts): PyTemplateOutput {
  const caps = opts.capabilities
    .split(',')
    .map((c) => c.trim())
    .filter(Boolean)
  const capsLit = `[${caps.map((c) => `"${c}"`).join(', ')}]`
  const modName = opts.name.replace(/-/g, '_')

  const pyproject = `[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "${opts.name}"
version = "0.1.0"
description = "AipeHub sidecar agent (${opts.id}) generated by aipehub-cli"
requires-python = ">=3.10"
dependencies = [
    "aipehub>=1.1.0",
]

[project.scripts]
${modName} = "${modName}.agent:main"

[tool.hatch.build.targets.wheel]
packages = ["src/${modName}"]

[tool.hatch.build.targets.sdist]
include = ["src"]
`

  const servicesImport = opts.includeServices
    ? `\n    ServiceOwner,\n    ServiceUseRequest,`
    : ''
  const servicesArg = opts.includeServices
    ? `,\n        services=[\n            ServiceUseRequest(\n                type="memory",\n                impl="file",\n                owner=ServiceOwner("agent", "self"),\n            ),\n        ]`
    : ''
  const servicesUsage = opts.includeServices
    ? `\n        # Example use of Hub Services. See docs/SIDECAR.md for the full guide.\n        # if self._session is not None and self._session.services is not None:\n        #     recent = await self._session.services.memory.recall({"k": 5})`
    : ''

  const source = `"""Sidecar agent for AipeHub — generated by \`aipehub new python-agent\`.

Run \`pip install -e .\` then \`python -m ${modName}\`. Connect to a Hub
via the AIPEHUB_URL env var (default ws://127.0.0.1:4000).

See docs/SIDECAR.md (AipeHub repo) for the full migration / services guide.
"""

from __future__ import annotations

import asyncio
import os

from aipehub import (
    AgentParticipant,${servicesImport}
    connect,
)


class ${pascal(opts.name)}Agent(AgentParticipant):
    def __init__(self) -> None:
        super().__init__(id="${opts.id}", capabilities=${capsLit})
        self._session = None  # populated after connect()

    async def handle_task(self, task: dict) -> dict:${servicesUsage}
        # Replace this with your real task handling.
        return {"echo": task.get("payload"), "by": self.id}


async def _main() -> None:
    url = os.environ.get("AIPEHUB_URL", "ws://127.0.0.1:4000")
    agent = ${pascal(opts.name)}Agent()
    session = await connect(
        url=url,
        agents=[agent]${servicesArg},
    )
    agent._session = session
    print(f"[${opts.id}] online — agentId=${opts.id}, capabilities=${caps.join(',') || '(none)'}")
    await session.wait_closed()


def main() -> None:
    asyncio.run(_main())


if __name__ == "__main__":
    main()
`

  const readme = `# ${opts.name}

AipeHub Python sidecar agent generated by \`aipehub new python-agent\`.
Connects to a Hub via WebSocket; default URL \`ws://127.0.0.1:4000\`
(override with the \`AIPEHUB_URL\` env var).

## Run

\`\`\`bash
python -m venv .venv
source .venv/bin/activate
pip install -e .
python -m ${modName}
\`\`\`

## Customise

Edit \`src/${modName}/agent.py\`:

- \`capabilities\` controls which tasks the Hub's scheduler will route
  to this agent.
- \`handle_task(task)\` is where your real work goes.
${opts.includeServices ? `- \`services\` declares which Hub Services you want to call. See
  the AipeHub docs/SIDECAR.md guide for the full menu.` : `- Re-add Hub Services support by following docs/SIDECAR.md if you
  later want \`memory\` / \`artifact\` / \`datastore\` access.`}

## Wire to a workflow

The Hub dispatches by capability. Make sure at least one of your
capability strings (${caps.length ? caps.map((c) => `\`${c}\``).join(', ') : '(none yet)'})
matches the workflow step you want to handle.
`

  return { pyproject, source, readme }
}

function pascal(s: string): string {
  return s
    .split(/[-_]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}
