/**
 * In-process template generator for `gotong new agent <name>`. Returns
 * the four files the scaffold writes. Pure function — no fs side
 * effects, so the templates are unit-testable on their own.
 */

export interface TsTemplateOpts {
  name: string
  id: string
  capabilities: string
  includeServices: boolean
}

export interface TsTemplateOutput {
  packageJson: string
  tsconfig: string
  source: string
  readme: string
}

export function renderTsTemplate(opts: TsTemplateOpts): TsTemplateOutput {
  const caps = opts.capabilities
    .split(',')
    .map((c) => c.trim())
    .filter(Boolean)
  const capsLit = JSON.stringify(caps)

  const packageJson = JSON.stringify(
    {
      name: opts.name,
      version: '0.1.0',
      type: 'module',
      private: true,
      description: `Gotong sidecar agent (${opts.id}) generated by gotong-cli`,
      main: 'dist/index.js',
      scripts: {
        build: 'tsc -p tsconfig.json',
        start: 'tsx src/index.ts',
        dev: 'tsx watch src/index.ts',
      },
      dependencies: {
        // Track the current published major. Pre-3.1 this was pinned
        // to `^2.0.0` — stale across the v3.0 release, so
        // `gotong new ts-agent foo && pnpm install` failed with
        // ERESOLVE for any new user. Bump alongside sdk-node majors.
        '@gotong/sdk-node': '^3.0.0',
      },
      devDependencies: {
        tsx: '^4.7.0',
        typescript: '^5.4.0',
      },
    },
    null,
    2,
  ) + '\n'

  const tsconfig = JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ES2022',
        moduleResolution: 'Bundler',
        lib: ['ES2022'],
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        outDir: 'dist',
        rootDir: 'src',
      },
      include: ['src/**/*'],
    },
    null,
    2,
  ) + '\n'

  const servicesImport = opts.includeServices
    ? `, type ServiceClient`
    : ''
  const servicesField = opts.includeServices
    ? `\n  services?: ServiceClient\n`
    : ''
  const servicesArg = opts.includeServices
    ? `\n  services: [\n    { type: 'memory', impl: 'file', owner: { kind: 'agent', id: 'self' } },\n  ],`
    : ''
  const servicesUsage = opts.includeServices
    ? `\n    // Example use of Hub Services. See docs/SIDECAR.md for the full guide.\n    // const recent = await this.services?.memory?.recall({ k: 5 })`
    : ''
  const servicesAttach = opts.includeServices
    ? `\nagent.services = session.services`
    : ''

  const source = `/**
 * Sidecar agent for Gotong — generated by \`gotong new agent\`.
 *
 * Run \`npm install && npm start\` and connect to a Hub via the
 * GOTONG_URL env var (default ws://127.0.0.1:4000).
 *
 * See docs/SIDECAR.md (Gotong repo) for the full migration / services guide.
 */

import { AgentParticipant, connect, type Task${servicesImport} } from '@gotong/sdk-node'

class ${pascal(opts.name)}Agent extends AgentParticipant {${servicesField}
  constructor() {
    super({ id: ${JSON.stringify(opts.id)}, capabilities: ${capsLit} })
  }

  protected async handleTask(task: Task): Promise<unknown> {${servicesUsage}
    // Replace this with your real task handling.
    return { echo: task.payload, by: this.id }
  }
}

const url = process.env.GOTONG_URL ?? 'ws://127.0.0.1:4000'
const agent = new ${pascal(opts.name)}Agent()

const session = await connect({
  url,
  agents: [agent],
  onStateChange: (state, info) => {
    console.log(\`[${opts.id}] \${state}\${info?.reason ? \` (\${info.reason})\` : ''}\`)
  },${servicesArg}
})${servicesAttach}

console.log(\`[${opts.id}] online — agentId=${opts.id}, capabilities=${caps.join(',') || '(none)'}\`)
`

  const readme = `# ${opts.name}

Gotong sidecar agent generated by \`gotong new agent\`. Connects to
a Hub via WebSocket; default URL \`ws://127.0.0.1:4000\` (override with
the \`GOTONG_URL\` env var).

## Run

\`\`\`bash
npm install
npm start
\`\`\`

## Customise

Edit \`src/index.ts\`:

- \`capabilities\` controls which tasks the Hub's scheduler will route
  to this agent.
- \`handleTask(task)\` is where your real work goes.
${opts.includeServices ? `- \`services\` declares which Hub Services you want to call. See
  the Gotong docs/SIDECAR.md guide for the full menu.` : `- Re-add Hub Services support by following docs/SIDECAR.md if you
  later want \`memory\` / \`artifact\` / \`datastore\` access.`}

## Wire to a workflow

The Hub dispatches by capability. Make sure at least one of your
capability strings (${caps.length ? caps.map((c) => `\`${c}\``).join(', ') : '(none yet)'})
matches the workflow step you want to handle.

## Build for production

\`\`\`bash
npm run build
node dist/index.js
\`\`\`

The agent is just a Node process — drop it on any host that can reach
the Hub's WebSocket port.
`

  return { packageJson, tsconfig, source, readme }
}

function pascal(s: string): string {
  return s
    .split(/[-_]/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}
