/**
 * Headless smoke for the esbuild-bundled `static/admin.js`.
 *
 * # Why this exists
 *
 * P3 moved the admin console source under `admin-src/` and now bundles it
 * through esbuild (IIFE format). esbuild prepends `"use strict";` and wraps
 * the file in its own IIFE — neither of which the hand-written admin.js
 * had. This smoke guards the two bundler-introduced risks that
 * `node --check` and the server-side route tests can't see:
 *
 *   1. the product *executes* under strict mode (a stray implicit global
 *      or octal literal throws only at run time, not at parse/--check time)
 *   2. the IIFE runs to completion — it destructures the window.AipeHub
 *      helpers, defines every handler, and registers its single
 *      DOMContentLoaded listener (the real init defers entirely to that
 *      callback, see admin-src/main.js)
 *
 * It deliberately does NOT drive the DOMContentLoaded init: that body is
 * unchanged source that esbuild copies verbatim, and faking the full
 * resolveDom() DOM would be brittle. Bundler correctness — not admin UI
 * behavior — is the target here.
 */

import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { runInNewContext } from 'node:vm'

const HERE = dirname(fileURLToPath(import.meta.url))
const ADMIN_JS = readFileSync(join(HERE, '..', 'static', 'admin.js'), 'utf8')

// The helpers admin-src/main.js destructures off window.AipeHub. Stubbed as
// noops so the IIFE's top-level destructure has a realistic namespace.
const AIPEHUB_HELPERS = [
  '$', 't', 'applyStaticI18n', 'onLangChange', 'escapeHtml', 'summarize',
  'isBadResult', 'fetchJson', 'connectStream', 'syncLangFromConfig',
  'fetchLeaderboard', 'renderLeaderboard', 'taskMetricsHtml', 'formatScore',
  'attachContribToggle', 'applyContribToggleState', 'attachCapChips',
]

function runBundle(): { domListeners: Record<string, unknown> } {
  const aipeHub: Record<string, unknown> = {}
  for (const h of AIPEHUB_HELPERS) aipeHub[h] = () => {}
  // The factory admin.js calls at init; return a no-op surface so a
  // top-level install (if any) doesn't throw.
  aipeHub.installWorkflowAssist = () => ({
    open() {}, close() {}, submit() {}, save() {},
  })
  const domListeners: Record<string, unknown> = {}
  const fakeEl = {
    style: {},
    dataset: {},
    classList: { add() {}, remove() {}, contains: () => false },
    hidden: true,
    textContent: '',
    innerHTML: '',
    value: '',
    appendChild() {}, setAttribute() {}, addEventListener() {},
  }
  const ctx = {
    window: {
      AipeHub: aipeHub,
      addEventListener: () => {},
      location: { hash: '', href: '' },
    },
    document: {
      addEventListener: (type: string, cb: unknown) => { domListeners[type] = cb },
      getElementById: () => null,
      querySelector: () => null,
      querySelectorAll: () => [],
      createElement: () => ({ ...fakeEl }),
      body: { appendChild() {} },
    },
    console,
    setTimeout: () => 0,
    clearTimeout: () => {},
    fetch: async () => ({ ok: true, status: 200, json: async () => ({}) }),
    EventSource: class { close() {} },
  }
  runInNewContext(ADMIN_JS, ctx)
  return { domListeners }
}

describe('static/admin.js — esbuild bundle smoke', () => {
  it('is the generated bundle (banner + strict mode + iife wrapper)', () => {
    expect(ADMIN_JS).toContain('AUTO-GENERATED by scripts/build-admin-ui.mjs')
    expect(ADMIN_JS).toContain('"use strict";')
    // esbuild stamps the entry path as a leading comment inside the IIFE.
    expect(ADMIN_JS).toContain('admin-src/main.js')
  })

  it('executes under strict mode without throwing and registers DOMContentLoaded', () => {
    let result: { domListeners: Record<string, unknown> } | undefined
    expect(() => { result = runBundle() }).not.toThrow()
    // The IIFE ran to completion if it got far enough to register the
    // single DOMContentLoaded listener that owns real init.
    expect(typeof result!.domListeners.DOMContentLoaded).toBe('function')
  })
})
