// AUTO-GENERATED by scripts/build-version.mjs. Do not edit by hand.
// Re-run `pnpm -C packages/host build:version` after bumping the
// version in package.json (or just `pnpm -r build` — the host's
// build script runs this generator before tsc).
//
// Why bake the version: in the bun --compile single-file binary,
// reading package.json from disk fails because it isn't on the
// embedded /$bunfs/ virtual filesystem. main.ts falls back to this
// constant whenever the disk read throws.

export const BAKED_VERSION = "3.2.0"
